package com.bortxapps.simplebleclient.exceptions

import androidx.annotation.Keep

@Keep
public enum class BleError {
    BLE_DEVICE_NOT_FOUND,
    CAMERA_NOT_CONNECTED,
    MISSING_BLE_PERMISSIONS,
    BLE_NOT_ENABLED,
    BLE_NOT_SUPPORTED,
    COMMUNICATION_FAILED,
    SEND_COMMAND_FAILED,
    UNABLE_TO_SUBSCRIBE_TO_NOTIFICATIONS,
    OTHER,
    CANNOT_START_SEARCHING_DEVICES,
    ALREADY_SEARCHING_BLE_DEVICES,
    UNABLE_INITIALIZE_CONTROLLER,
    BLE_DEVICE_NOT_RESPONDING,
    INTERNAL_ERROR,
    LIBRARY_NOT_INITIALIZED
}
