name: Android publish

on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Decode Keystore
        run: pwd; echo ${{ secrets.ENCODED_KEYSTORE }} | base64 -d > bortxappskeystore.p12

      - name: Set up env variables
        run: |
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ENCODED_KEYSTORE=${{ secrets.ENCODED_KEYSTORE }}" >> $GITHUB_ENV
          echo "KEYSTORE_PATH=${{ secrets.KEYSTORE_PATH }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build and Sign AAR
        run: ./gradlew assembleRelease