name: Android Validations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Compile the project
        run: ./gradlew assembleDebug
      - name: Run unit tests
        run: ./gradlew test
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
      - name: Run KLint
        run: ./gradlew ktlintCheck
      - name: Run Detekt
        run: ./gradlew detekt
